-- ============================================================================
-- Future of NYC Design 2026 — Acknowledgments Reel (cluster format)
-- ============================================================================
-- Companion to fond_2026_event.sql + fond_2026_segments.sql.
--
-- Drives the 12:00–12:30 opening and 19:15–20:00 reception windows on
-- 2026-05-16 with a 3-scene playlist that rotates a clustered-logo view of
-- each acknowledgment group:
--
--     Cluster — Presenters             (4 logos on an arc, "Presented By")
--     Cluster — Sponsors               (3 logos on an arc, "Sponsored By")
--     Cluster — Community Partners     (6 logos on an arc, "In Partnership With")
--
-- Why this file ALSO carries fixups for the upstream seed:
--   On 2026-05-15 the live DB was audited and found to be missing the four
--   bbbb-…-0001..0004 presenter scenes, the daytime Sponsor Reel playlist
--   had no scenes attached, and org_settings.force_play_scene_id was still
--   pinned to the Design Awards scene. Those are fixed here too so the
--   schedule actually drives playback on the day.
--
-- LOGO HOSTING
--   • Presenter logos live on futureofnycdesign.com/public/logos/.
--   • Sponsor + community-partner logos live in the Supabase Storage
--     `overlay-images` bucket under fond2026/{sponsors,partners}/ (public).
--   The speaker-cluster components in both renderers recognise both URL
--   prefixes as logo nodes (object-fit: contain + padded background) — see
--   the isLogoUrl helper in web/components/SpeakerCluster.tsx and
--   electron-app/src/renderer/CompositionLayer.tsx.
--
-- BACKDROP
--   All 3 cluster scenes share the same backdrop currently serving Arrival
--   + Registration (.../19fb9f7f-…mp4). Retarget per-scene later if needed.
--
-- RE-RUNNING
--   Explicit UUIDs + ON CONFLICT (DO NOTHING for inserts, DO UPDATE for the
--   cluster scenes so their composition can be regenerated by re-running).
--   Schedule UPDATEs match on old value so a rerun after rollback is safe.
-- ============================================================================

begin;

-- ----------------------------------------------------------------------------
-- 0. Clear the force-play override.
-- ----------------------------------------------------------------------------
update org_settings
   set force_play_scene_id = null
 where org_id = '00000000-0000-0000-0000-000000000001';

-- ----------------------------------------------------------------------------
-- 1. Pseudo-speaker photo URLs → absolute. The /logos/<group>/<file> seed
--    paths only resolve from the Next dashboard; the Electron renderer
--    loads via file:// and can't see them. Rewriting to absolute URLs keeps
--    both renderers in sync.
-- ----------------------------------------------------------------------------
update speakers set photo_url = 'https://www.futureofnycdesign.com/public/logos/vibes.png'                        where id = 'dddddddd-7777-7777-7777-000000000001';
update speakers set photo_url = 'https://www.futureofnycdesign.com/public/logos/241members.png'                   where id = 'dddddddd-7777-7777-7777-000000000002';
update speakers set photo_url = 'https://www.futureofnycdesign.com/public/logos/sanders_studio_transparent.png'   where id = 'dddddddd-7777-7777-7777-000000000003';
update speakers set photo_url = 'https://www.futureofnycdesign.com/public/logos/visionbrew_transparent.png'       where id = 'dddddddd-7777-7777-7777-000000000004';
update speakers set photo_url = 'https://arnfcguwmsgazpsybvth.supabase.co/storage/v1/object/public/overlay-images/fond2026/sponsors/Figma.png'      where id = 'dddddddd-7777-7777-7777-000000000005';
update speakers set photo_url = 'https://arnfcguwmsgazpsybvth.supabase.co/storage/v1/object/public/overlay-images/fond2026/sponsors/mobbin.svg'     where id = 'dddddddd-7777-7777-7777-000000000006';
update speakers set photo_url = 'https://arnfcguwmsgazpsybvth.supabase.co/storage/v1/object/public/overlay-images/fond2026/sponsors/wonder.svg'     where id = 'dddddddd-7777-7777-7777-000000000007';
update speakers set photo_url = 'https://arnfcguwmsgazpsybvth.supabase.co/storage/v1/object/public/overlay-images/fond2026/partners/AIGA-NY.png'    where id = 'dddddddd-7777-7777-7777-000000000008';
update speakers set photo_url = 'https://arnfcguwmsgazpsybvth.supabase.co/storage/v1/object/public/overlay-images/fond2026/partners/acf.png'        where id = 'dddddddd-7777-7777-7777-000000000009';
update speakers set photo_url = 'https://arnfcguwmsgazpsybvth.supabase.co/storage/v1/object/public/overlay-images/fond2026/partners/bkpd.png'       where id = 'dddddddd-7777-7777-7777-000000000010';
update speakers set photo_url = 'https://arnfcguwmsgazpsybvth.supabase.co/storage/v1/object/public/overlay-images/fond2026/partners/bsm.png'        where id = 'dddddddd-7777-7777-7777-000000000011';
update speakers set photo_url = 'https://arnfcguwmsgazpsybvth.supabase.co/storage/v1/object/public/overlay-images/fond2026/partners/her-rising.png' where id = 'dddddddd-7777-7777-7777-000000000012';
update speakers set photo_url = 'https://arnfcguwmsgazpsybvth.supabase.co/storage/v1/object/public/overlay-images/fond2026/partners/friends-of-figma.svg' where id = 'dddddddd-7777-7777-7777-000000000013';

-- ----------------------------------------------------------------------------
-- 2. Daytime transition slots all share the Acknowledgments Reel.
--    fond_2026_event.sql originally pointed 5 transition entries at the
--    "Sponsor Reel" playlist, but its scenes never reached prod. Rather
--    than recreating a second reel, every transition now uses the same
--    cluster reel so sponsors/partners get steady visibility across the
--    day. The Sponsor Reel playlist row is dropped at the bottom.
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- 3. Cluster scenes (Presenters / Sponsors / Community Partners).
--    Each scene's composition.speakerCluster is built from the matching
--    segment in fond_2026_segments.sql — single source of truth for who's
--    in each group.
-- ----------------------------------------------------------------------------
with built as (
  select
    seg.id as segment_id, seg.title, seg.subtitle,
    jsonb_agg(
      jsonb_build_object(
        'photoUrl', sp.photo_url,
        'name',     sp.name,
        'role',     ss.role,
        'key',      sp.id::text
      ) order by ss.position
    ) as items
  from segments seg
  join segment_speakers ss on ss.segment_id = seg.id
  join speakers sp on sp.id = ss.speaker_id
  where seg.id in (
    'ffffffff-6666-6666-6666-000000000007'::uuid,
    'ffffffff-6666-6666-6666-000000000008'::uuid,
    'ffffffff-6666-6666-6666-000000000009'::uuid)
  group by seg.id, seg.title, seg.subtitle
),
target as (
  select
    case segment_id
      when 'ffffffff-6666-6666-6666-000000000007'::uuid then 'aaaaaaaa-1111-1111-1111-000000000020'::uuid
      when 'ffffffff-6666-6666-6666-000000000008'::uuid then 'aaaaaaaa-1111-1111-1111-000000000021'::uuid
      when 'ffffffff-6666-6666-6666-000000000009'::uuid then 'aaaaaaaa-1111-1111-1111-000000000022'::uuid
    end as scene_id,
    case segment_id
      when 'ffffffff-6666-6666-6666-000000000007'::uuid then 'Cluster — Presenters'
      when 'ffffffff-6666-6666-6666-000000000008'::uuid then 'Cluster — Sponsors'
      when 'ffffffff-6666-6666-6666-000000000009'::uuid then 'Cluster — Community Partners'
    end as scene_name,
    title, subtitle, items
  from built
)
insert into scenes (id, org_id, name, video_url, hide_attribution, loop_enabled, composition)
select
  scene_id, '00000000-0000-0000-0000-000000000001', scene_name,
  'https://arnfcguwmsgazpsybvth.supabase.co/storage/v1/object/public/scenes-videos/00000000-0000-0000-0000-000000000001/19fb9f7f-5b03-44f9-8abe-1ca5585e2554.mp4',
  false, false,
  jsonb_build_object(
    'zones', jsonb_build_object(
      'header', jsonb_build_object('imageUrl', null, 'position', 'center'),
      'center', jsonb_build_object('imageUrl', null, 'position', 'center'),
      'footer', jsonb_build_object('imageUrl', null, 'position', 'center')
    ),
    'caption', jsonb_build_object(
      'text', upper(subtitle) || E'\n' || title,
      'font', 'bebas', 'size', 48, 'color', '#F0EAF5',
      'h', 'center', 'v', 'bottom'
    ),
    'tint', jsonb_build_object('color', '#000000', 'opacity', 40),
    'accent', null,
    'speakerCluster', jsonb_build_object('items', items),
    'branding', jsonb_build_object('enabled', true)
  )
from target
on conflict (id) do update set
  name        = excluded.name,
  composition = excluded.composition,
  video_url   = excluded.video_url,
  loop_enabled = excluded.loop_enabled;

-- ----------------------------------------------------------------------------
-- 4. Acknowledgments Reel playlist — 3 cluster scenes in display order.
-- ----------------------------------------------------------------------------
insert into playlists (id, org_id, name) values
  ('cccccccc-3333-3333-3333-000000000002'::uuid, '00000000-0000-0000-0000-000000000001', 'Acknowledgments Reel')
on conflict (id) do nothing;

-- Drop any previous contents (the earlier 12-brand-card iteration) before
-- repopulating with the 3 cluster scenes.
delete from playlist_scenes
 where playlist_id = 'cccccccc-3333-3333-3333-000000000002'::uuid;

insert into playlist_scenes (playlist_id, scene_id, position) values
  ('cccccccc-3333-3333-3333-000000000002'::uuid, 'aaaaaaaa-1111-1111-1111-000000000020'::uuid, 0),  -- Presenters
  ('cccccccc-3333-3333-3333-000000000002'::uuid, 'aaaaaaaa-1111-1111-1111-000000000021'::uuid, 1),  -- Sponsors
  ('cccccccc-3333-3333-3333-000000000002'::uuid, 'aaaaaaaa-1111-1111-1111-000000000022'::uuid, 2); -- Community Partners

-- ----------------------------------------------------------------------------
-- 5. Schedule entries — Opening, Reception, AND every daytime transition
--    all point at the Acknowledgments Reel.
-- ----------------------------------------------------------------------------
update schedule_entries
   set scene_id    = null,
       playlist_id = 'cccccccc-3333-3333-3333-000000000002'::uuid
 where id = 'dddddddd-4444-4444-4444-000000000001'::uuid
   and (scene_id = 'aaaaaaaa-1111-1111-1111-000000000001'::uuid or playlist_id is null);

update schedule_entries
   set scene_id    = null,
       playlist_id = 'cccccccc-3333-3333-3333-000000000002'::uuid
 where id = 'dddddddd-4444-4444-4444-000000000016'::uuid
   and (scene_id = 'aaaaaaaa-1111-1111-1111-000000000011'::uuid or playlist_id is null);

-- Daytime transitions originally pointed at the empty Sponsor Reel; route
-- them to the Acknowledgments Reel too.
update schedule_entries
   set playlist_id = 'cccccccc-3333-3333-3333-000000000002'::uuid
 where org_id = '00000000-0000-0000-0000-000000000001'
   and playlist_id = 'cccccccc-3333-3333-3333-000000000001'::uuid;

-- Drop the now-orphaned Sponsor Reel playlist row.
delete from playlist_scenes where playlist_id = 'cccccccc-3333-3333-3333-000000000001'::uuid;
delete from playlists       where id          = 'cccccccc-3333-3333-3333-000000000001'::uuid;

commit;

-- ============================================================================
-- VERIFICATION
-- ============================================================================
-- 1. select force_play_scene_id from org_settings where org_id = '00000000-0000-0000-0000-000000000001';
--    -> null
-- 2. select count(*) from playlist_scenes where playlist_id = 'cccccccc-3333-3333-3333-000000000001';  -- 4 (Sponsor Reel)
-- 3. select count(*) from playlist_scenes where playlist_id = 'cccccccc-3333-3333-3333-000000000002';  -- 3 (Acknowledgments Reel)
-- 4. Dashboard /schedule → 12:00–12:30 and 19:15–20:00 show "Acknowledgments Reel".
-- 5. Open /preview during one of those windows (override the system clock) and
--    confirm the three clusters rotate.

-- ============================================================================
-- ROLLBACK
-- ============================================================================
-- begin;
-- update schedule_entries set scene_id = 'aaaaaaaa-1111-1111-1111-000000000001'::uuid, playlist_id = null
--   where id = 'dddddddd-4444-4444-4444-000000000001'::uuid;
-- update schedule_entries set scene_id = 'aaaaaaaa-1111-1111-1111-000000000011'::uuid, playlist_id = null
--   where id = 'dddddddd-4444-4444-4444-000000000016'::uuid;
-- delete from playlist_scenes where playlist_id = 'cccccccc-3333-3333-3333-000000000002'::uuid;
-- delete from playlists       where id          = 'cccccccc-3333-3333-3333-000000000002'::uuid;
-- delete from scenes where id in (
--   'aaaaaaaa-1111-1111-1111-000000000020'::uuid,
--   'aaaaaaaa-1111-1111-1111-000000000021'::uuid,
--   'aaaaaaaa-1111-1111-1111-000000000022'::uuid);
-- delete from playlist_scenes where playlist_id = 'cccccccc-3333-3333-3333-000000000001'::uuid;
-- delete from scenes where id in (
--   'bbbbbbbb-2222-2222-2222-000000000001'::uuid,
--   'bbbbbbbb-2222-2222-2222-000000000002'::uuid,
--   'bbbbbbbb-2222-2222-2222-000000000003'::uuid,
--   'bbbbbbbb-2222-2222-2222-000000000004'::uuid);
-- commit;
